export const CLIENT = {
  name: "Meridian Financial Group",
  industry: "Financial Services",
  aiSystem: "Internal Analytics Assistant",
  deployment: "Azure OpenAI (GPT-4o), Snowflake data warehouse",
};

// severity: "red" | "yellow" | "green"
export const LAYERS = [
  {
    id: "data",
    label: "Data Warehouse",
    subtitle: "Snowflake",
    icon: "⬡",
    summary: "Critical access control gaps with overprivileged service accounts, no row-level security, no prompt retention policy, and unrotated secrets.",
    findings: [
      {
        control: "Row Access Policies",
        expected: "Row-level security policies enforced per user role",
        actual: "No row access policies defined",
        severity: "red",
        remediation: "Define row access policies on all schemas containing PII or financial data. Map policies to existing AD roles via RBAC integration.",
      },
      {
        control: "Column Masking — SSN",
        expected: "SSN column masked for non-privileged roles",
        actual: "SSN column unmasked for ANALYST_ROLE",
        severity: "red",
        remediation: "Apply dynamic data masking policy on SSN column. Grant unmask privilege only to COMPLIANCE_ROLE with audit logging.",
      },
      {
        control: "AI Service Role Privileges",
        expected: "AI_SERVICE_ROLE scoped to required schemas only",
        actual: "AI_SERVICE_ROLE has SELECT on all schemas — overprivileged",
        severity: "red",
        remediation: "Restrict AI_SERVICE_ROLE to FINANCE.PUBLIC and ANALYTICS schemas only. Implement query tagging to trace AI-originated queries.",
      },
      {
        control: "Data Quality Validation",
        expected: "Validation rules enforced at ingestion pipeline",
        actual: "No validation rules on ingestion pipeline",
        severity: "yellow",
        remediation: "Implement schema validation and null-check constraints on the ingestion pipeline. Add data quality monitoring alerts.",
      },
      {
        control: "Identity Propagation",
        expected: "End-user identity propagated through to warehouse queries",
        actual: "AI_SERVICE_ROLE used for all queries regardless of requesting user",
        severity: "red",
        remediation: "Implement session-level identity propagation using Snowflake session variables. Tag every query with the originating user's identity.",
      },
      {
        control: "Prompt & Response Retention Policy",
        expected: "30-day retention of prompt/response pairs for security, legal, and workplace safety purposes only. No use for analytics, benchmarking, or debugging without explicit approval.",
        actual: "No prompt retention policy defined — responses are not stored, and no retention window is configured",
        severity: "red",
        remediation: "Implement 30-day rolling retention of hashed prompt/response pairs in an immutable store. Restrict access to security, privacy, and legal teams only. Prohibit use for application analytics, benchmarking, troubleshooting, or debugging without explicit security/privacy/legal sign-off.",
      },
      {
        control: "Scoped IAM Policies",
        expected: "All service roles follow least-privilege IAM policies scoped to specific resources",
        actual: "AI_SERVICE_ROLE uses broad IAM permissions — not scoped to specific Snowflake schemas or Azure resources",
        severity: "red",
        remediation: "Audit and scope down all IAM policies to minimum required permissions. Apply resource-level conditions. Implement IAM policy drift detection with automated alerts.",
      },
      {
        control: "Secret Rotation",
        expected: "All API keys, service credentials, and connection strings rotated on schedule with no hardcoded secrets",
        actual: "Snowflake service account credentials have not been rotated in 6 months. Azure OpenAI API key stored in environment variable without rotation policy.",
        severity: "red",
        remediation: "Move all secrets to a managed vault (Azure Key Vault). Implement automated rotation on a 90-day cycle. Ensure API keys are used only for rate limiting, not authentication.",
      },
      {
        control: "Vendor Data Training Restrictions",
        expected: "All third-party AI vendors contractually restricted from using organizational data for model training without explicit written consent",
        actual: "No contractual restrictions in place — default vendor terms apply, which may allow data use for model improvement",
        severity: "red",
        remediation: "Review all AI vendor contracts. Add explicit data training opt-out clauses. Verify Azure OpenAI Enterprise Agreement includes abuse monitoring opt-out. Require written confirmation from each vendor that organizational data will not be used for model training.",
      },
      {
        control: "AI Data Classification Policy",
        expected: "Documented data classification policy defining which data categories are permitted for AI system use",
        actual: "No AI-specific data classification policy exists — general data classification policy does not address AI use cases",
        severity: "red",
        remediation: "Extend existing data classification policy to include AI-specific provisions: define permitted data categories per risk tier, establish approval requirements for sensitive data use in AI, and publish clear guidance on prohibited data categories (e.g., no customer PII in training data without consent).",
      },
      {
        control: "AI Data Retention & Deletion",
        expected: "Retention and deletion policies specifically defined for AI training data, prompt logs, and model artifacts",
        actual: "No AI-specific retention policies — prompt logs and model artifacts have no defined retention window or deletion schedule",
        severity: "red",
        remediation: "Define retention policies for: (a) prompt/response logs — 30-day rolling window for security purposes, (b) training data — retention tied to model lifecycle with deletion upon model retirement, (c) model artifacts — version-controlled with defined archival and deletion schedules.",
      },
    ],
  },
  {
    id: "semantic",
    label: "Semantic Layer",
    subtitle: "Metrics & Definitions",
    icon: "◈",
    summary: "74% of metrics are uncertified and in production use. No version control or conflict detection.",
    findings: [
      {
        control: "Metric Certification Rate",
        expected: "All production metrics formally certified",
        actual: "12 of 47 metrics certified (25.5%) — 35 draft/experimental metrics in production use",
        severity: "red",
        remediation: "Freeze production use of uncertified metrics. Establish a certification workflow requiring data owner sign-off before promotion.",
      },
      {
        control: "Version Control",
        expected: "Metric definitions version-controlled in Git",
        actual: "No Git integration — definitions stored in application database only",
        severity: "red",
        remediation: "Export all metric definitions to a Git repository. Implement CI/CD pipeline for definition changes with review gates.",
      },
      {
        control: "Metric Ownership",
        expected: "Every metric has a designated business owner",
        actual: "8 of 47 metrics have assigned owners",
        severity: "yellow",
        remediation: "Assign owners to all 47 metrics. Implement quarterly ownership review cadence. Unowned metrics should be flagged for deprecation.",
      },
      {
        control: "Conflict Detection",
        expected: "Automated detection of divergent KPI definitions across teams",
        actual: "No conflict detection — ANALYST_ROLE and EXEC_ROLE return different values for 'Revenue'",
        severity: "red",
        remediation: "Run a full conflict scan across all role-metric combinations. Standardize Revenue definition. Implement automated divergence detection in CI.",
      },
    ],
  },
  {
    id: "vector",
    label: "Vector Database",
    subtitle: "Retrieval Layer",
    icon: "◎",
    summary: "Document retrieval has no access scoping. PII detected in indexed HR documents. No output validation before downstream systems.",
    findings: [
      {
        control: "Access Tag Coverage",
        expected: "All indexed documents tagged with access control metadata",
        actual: "312 of 1,247 documents tagged (25%)",
        severity: "yellow",
        remediation: "Implement mandatory access tagging in the document indexing pipeline. Backfill tags for existing 935 untagged documents.",
      },
      {
        control: "Retrieval Scope Enforcement",
        expected: "Users can only retrieve documents within their access scope",
        actual: "No scope enforcement — all users can retrieve all documents",
        severity: "red",
        remediation: "Implement pre-retrieval access filter using document access tags and user role mapping. Block retrieval of untagged documents by default.",
      },
      {
        control: "Chunk Provenance Logging",
        expected: "Every retrieved chunk logged with source document ID and retrieval context",
        actual: "No provenance logging implemented",
        severity: "red",
        remediation: "Add provenance metadata to every retrieval response: source document ID, chunk index, retrieval score, and requesting user.",
      },
      {
        control: "PII in Indexed Documents",
        expected: "No PII in document index without explicit classification",
        actual: "3 HR policy documents contain employee PII (names, SSNs)",
        severity: "red",
        remediation: "Remove PII-containing documents from index immediately. Implement PII scanning in the indexing pipeline. Re-index after remediation.",
      },
      {
        control: "Output Validation Gate",
        expected: "All AI-generated content validated and filtered before flowing into downstream systems (reports, databases, APIs)",
        actual: "AI responses can be exported directly to internal dashboards and Slack channels without validation",
        severity: "red",
        remediation: "Implement an output validation gate between the AI system and any downstream consumers. Apply content classification, PII scanning, and confidence threshold checks before any AI output is written to another system or shared externally.",
      },
    ],
  },
  {
    id: "model",
    label: "LLM / Model Layer",
    subtitle: "Azure OpenAI",
    icon: "◉",
    summary: "No guardrails, no evaluation pipeline, no kill switch, no model legal approval, no security testing, and prompts may be used for provider abuse monitoring.",
    findings: [
      {
        control: "System Prompt Guardrails",
        expected: "System prompt includes behavioral constraints and output formatting rules",
        actual: "Basic role description only — no behavioral guardrails",
        severity: "yellow",
        remediation: "Enhance system prompt with explicit behavioral constraints: scope limitations, refusal patterns for out-of-scope queries, and output formatting requirements.",
      },
      {
        control: "Direct Prompt Injection Defenses",
        expected: "Input sanitization, regex filtering, and prompt attack detection active for user-submitted queries (e.g. 'ignore previous instructions', system prompt extraction attempts)",
        actual: "No prompt injection defenses implemented — no input sanitization, no WAF rules, no attack classifier",
        severity: "red",
        remediation: "Implement a multi-layer defense: (1) WAF with regex filters for known injection patterns (use safe regexes — verify against ReDoS). (2) Prompt attack detection classifier as a pre-processing step. (3) Input sanitization restricting to safe character sets where feasible. Log all blocked attempts.",
      },
      {
        control: "Indirect Prompt Injection Defenses",
        expected: "RAG documents and external inputs scanned for embedded instructions before inclusion in model context",
        actual: "No scanning of retrieved documents for embedded prompt injection payloads",
        severity: "red",
        remediation: "Implement content scanning on all RAG-sourced inputs before they enter the model context window. Flag documents containing instruction-like patterns. Quarantine and review flagged content before re-indexing.",
      },
      {
        control: "Confidence Scoring",
        expected: "Every response includes a calibrated confidence score",
        actual: "Not implemented",
        severity: "red",
        remediation: "Implement confidence scoring using token probability analysis. Route low-confidence responses (< 0.70) to human review queue.",
      },
      {
        control: "Citation Enforcement",
        expected: "Every factual claim in responses must cite a source document",
        actual: "Not implemented",
        severity: "red",
        remediation: "Add citation enforcement in the response generation pipeline. Require source document references for all factual claims. Flag uncitable responses.",
      },
      {
        control: "Content Safety API",
        expected: "Azure Content Safety API configured and active",
        actual: "Not configured",
        severity: "red",
        remediation: "Enable Azure Content Safety API with appropriate thresholds. Configure category-specific filters for financial services context.",
      },
      {
        control: "Evaluation Pipeline",
        expected: "Automated correctness and compliance checks on model outputs",
        actual: "No evaluation pipeline exists",
        severity: "red",
        remediation: "Build evaluation pipeline with automated test suites: factual accuracy, compliance language, scope adherence. Run on every model update.",
      },
      {
        control: "Azure Data Processing Terms",
        expected: "Enterprise Agreement with abuse monitoring opt-out active",
        actual: "Standard tier — prompts may be used for abuse monitoring",
        severity: "yellow",
        remediation: "Upgrade to Enterprise Agreement with abuse monitoring opt-out. Review Azure data processing addendum with legal team.",
      },
      {
        control: "Andon Cord — AI Kill Switch",
        expected: "Mechanism to disable all GenAI functionality independently of the model provider, with a generic error message to users",
        actual: "No kill switch exists — disabling AI requires a full application deployment or Azure service suspension",
        severity: "red",
        remediation: "Implement an application-level feature flag that immediately disables all GenAI functionality without depending on Azure. Display a standardized fallback message: 'AI features are temporarily unavailable. Please contact support.' Test the kill switch quarterly.",
      },
      {
        control: "Pre-Trained Model Legal Approval",
        expected: "All foundation models in use have documented legal approval covering IP, licensing, and data processing terms",
        actual: "No legal review on file for GPT-4o usage — deployment proceeded without formal model approval",
        severity: "red",
        remediation: "Submit legal review request for GPT-4o covering: licensing terms, IP ownership of outputs, data processing agreement, and approved use cases. Block new model deployments until legal sign-off is obtained.",
      },
      {
        control: "Security Testing Pipeline",
        expected: "Automated adversarial security tests (prompt injection, data exfiltration, jailbreak) running in CI/CD pipeline",
        actual: "No security-specific tests in pipeline — only functional tests exist",
        severity: "red",
        remediation: "Integrate adversarial prompt testing into the CI/CD pipeline. Include test suites for: prompt injection (direct and indirect), data exfiltration attempts, jailbreak patterns, and system prompt extraction. Run on every deployment.",
      },
      {
        control: "Bias & Fairness Testing Framework",
        expected: "Automated bias and fairness evaluation framework that tests AI outputs for discrimination across protected characteristics (race, gender, age, disability, religion, sexual orientation, national origin)",
        actual: "No bias or fairness testing exists — model outputs are not evaluated for discriminatory patterns",
        severity: "red",
        remediation: "Implement a bias and fairness testing framework: (1) Define fairness metrics (demographic parity, equalized odds, calibration) appropriate to each use case. (2) Build test suites using demographic-varied inputs. (3) Run fairness evaluations on every model update. (4) Establish acceptable thresholds with Legal and Compliance sign-off. (5) Block deployment if thresholds are exceeded.",
      },
      {
        control: "Prohibited Use Case Enforcement",
        expected: "Explicitly documented list of prohibited AI use cases with technical controls to prevent deployment",
        actual: "No documented prohibited use cases — no technical controls to block prohibited applications",
        severity: "red",
        remediation: "Document all prohibited AI use cases aligned with the AI Constitution (e.g., emotional monitoring, social scoring, subliminal manipulation, biometric identification without consent). Implement technical enforcement: intake form hard-blocks for prohibited categories, deployment gate checks, and quarterly audit of active systems against the prohibited list.",
      },
      {
        control: "Third-Party Vendor AI Risk Review",
        expected: "Formal vendor AI risk assessment process required before procuring or integrating any external AI capability",
        actual: "No vendor-specific AI risk assessment exists — AI vendors evaluated using standard procurement process without AI-specific criteria",
        severity: "red",
        remediation: "Establish a Third-Party AI Vendor Assessment process that evaluates: vendor AI governance framework, risk classification, data handling practices (including model training), explainability and auditability, incident response obligations, contractual protections, and ongoing monitoring obligations. No vendor approval bypasses this process.",
      },
      {
        control: "Model Drift Detection",
        expected: "Continuous monitoring for model drift — automated detection when AI behavior or performance changes without code updates",
        actual: "No drift detection implemented — model performance is not baselined or monitored over time",
        severity: "yellow",
        remediation: "Establish performance baselines for all production AI models. Implement drift detection monitoring: track output distribution, confidence score trends, and response pattern changes. Set automated alerts when metrics deviate beyond defined thresholds. Schedule quarterly model performance reviews.",
      },
    ],
  },
  {
    id: "app",
    label: "Application Layer",
    subtitle: "User-Facing Controls",
    icon: "◇",
    summary: "Strong authentication in place, but no audit logging, human review, AI disclosure, disclaimer, security headers, rate limiting, or session isolation.",
    findings: [
      {
        control: "Authentication",
        expected: "SSO with enterprise identity provider",
        actual: "Azure AD SSO implemented",
        severity: "green",
        remediation: "No action required. SSO is properly configured.",
      },
      {
        control: "Multi-Factor Authentication",
        expected: "MFA enforced for all users",
        actual: "MFA enforced via Azure AD Conditional Access",
        severity: "green",
        remediation: "No action required. MFA is properly enforced.",
      },
      {
        control: "Structured Audit Logging",
        expected: "Every query/response pair logged with user ID, timestamp, and metadata",
        actual: "Basic application logs only — no structured query/response logging",
        severity: "red",
        remediation: "Implement structured audit logging: user ID, timestamp, query text (hashed), response hash, confidence score, retrieval sources. Store in immutable log.",
      },
      {
        control: "Human Review Queue",
        expected: "Low-confidence and high-risk responses routed for human review",
        actual: "No human review queue exists",
        severity: "red",
        remediation: "Build human review queue with configurable routing rules. Route responses with confidence < 0.70 and all financial/compliance queries for review.",
      },
      {
        control: "Anomaly Detection",
        expected: "Behavioral anomaly detection on query patterns",
        actual: "No anomaly detection implemented",
        severity: "red",
        remediation: "Implement anomaly detection on query volume, topic distribution, and access patterns. Alert on statistical deviations from baseline.",
      },
      {
        control: "Employee AI Usage Disclosure",
        expected: "AI usage policy communicated to all employees with acknowledgment",
        actual: "No AI usage policy communicated to employees",
        severity: "red",
        remediation: "Draft and distribute AI Transparency & Usage Policy. Require employee acknowledgment. Include: what is logged, who can access logs, employee rights.",
      },
      {
        control: "Gen AI Disclaimer Banner",
        expected: "Persistent in-app disclaimer stating: approved data classification level, prohibition on customer data input, notice that outputs require independent verification, and notice that prompts may be used to improve the system",
        actual: "No disclaimer or data classification guidance displayed to users",
        severity: "red",
        remediation: "Add a persistent disclaimer banner visible on every AI interaction screen. Include: approved data classification (Internal only — no customer data), verification requirement for all AI outputs, prompt usage notice, and link to full AI usage policy.",
      },
      {
        control: "Security Headers (CSP / XSS)",
        expected: "Content Security Policy, X-Frame-Options, X-Content-Type-Options, and Strict-Transport-Security headers configured to mitigate XSS, clickjacking, and data injection attacks",
        actual: "No security headers configured — default server headers only",
        severity: "red",
        remediation: "Configure CSP header with strict source directives. Add X-Frame-Options: DENY, X-Content-Type-Options: nosniff, and HSTS with min 1-year max-age. Validate headers with a security scanner.",
      },
      {
        control: "DDoS / Rate Limiting",
        expected: "Rate limiting enforced per user and per IP on all AI query endpoints to prevent abuse and resource exhaustion",
        actual: "No rate limiting on AI query endpoints — users can submit unlimited requests",
        severity: "red",
        remediation: "Implement rate limiting at the API gateway level: per-user (e.g. 30 queries/min) and per-IP. Add progressive backoff for repeated limit hits. Configure WAF rules for volumetric attack patterns. Use API keys for throttling only, not authentication.",
      },
      {
        control: "User Session Isolation",
        expected: "Each user session is fully isolated — no cross-session context leakage between users",
        actual: "Session isolation not formally verified — shared AI_SERVICE_ROLE creates risk of context bleed",
        severity: "yellow",
        remediation: "Implement strict session isolation at the application layer. Ensure conversation context, retrieved documents, and model state are scoped to individual authenticated sessions. Audit for cross-session leakage.",
      },
      {
        control: "AI Transparency Disclosure",
        expected: "End users are clearly informed when they are interacting with AI-generated content, with visible disclosure on every AI interaction screen",
        actual: "No transparency disclosure — users are not informed when content is AI-generated vs. human-authored",
        severity: "red",
        remediation: "Implement AI transparency disclosures: (1) Persistent indicator on all AI-generated responses. (2) Clear labeling distinguishing AI outputs from human-authored content. (3) Disclosure notice on first use explaining AI involvement. Aligned with EU AI Act transparency requirements.",
      },
      {
        control: "AI Literacy & Training Program",
        expected: "Role-based AI literacy and responsible use training program with defined completion requirements for all employees who interact with AI systems",
        actual: "No AI-specific training program exists — employees use AI tools without formal training on responsible use, limitations, or governance requirements",
        severity: "red",
        remediation: "Develop and deploy role-based AI training: (1) General workforce — AI literacy, responsible use policy, data handling do's and don'ts. (2) Technical teams — model evaluation, bias awareness, security best practices. (3) Leadership — governance responsibilities, risk oversight, accountability. Set completion requirements and track compliance.",
      },
      {
        control: "AI Concern Reporting Channels",
        expected: "Clear, accessible channels for employees to raise AI-related concerns (bias, safety, misuse, policy violations) without adverse consequences",
        actual: "No dedicated AI concern reporting channel — employees must use general HR or compliance reporting with no AI-specific guidance",
        severity: "yellow",
        remediation: "Establish dedicated AI concern reporting channels: (1) Designated intake mechanism (form, email alias, or reporting tool). (2) Clear guidance on what constitutes a reportable AI concern. (3) Documented non-retaliation policy. (4) Defined SLAs for acknowledgment and investigation. (5) Regular communication from leadership reinforcing speak-up culture.",
      },
      {
        control: "AI Decision Authority Matrix (RACI)",
        expected: "Documented RACI matrix assigning accountability for AI outcomes at every organizational level — from use case owner to executive sponsor to governance body",
        actual: "No AI-specific RACI exists — decision authority for AI systems is informal and ad hoc",
        severity: "red",
        remediation: "Define and publish an AI Decision Authority Matrix covering: use case registration (who approves), risk tier escalation (who decides), deployment gates (who signs off), incident response (who owns), and ongoing monitoring (who is accountable). Map to existing org structure and integrate with AI Governance Body charter.",
      },
      {
        control: "Vendor Governance & Monitoring",
        expected: "Formal process for evaluating and approving AI vendor relationships with ongoing monitoring and contractual governance obligations",
        actual: "No AI-specific vendor governance — vendors are evaluated using standard procurement without AI risk criteria or ongoing AI monitoring",
        severity: "red",
        remediation: "Implement AI vendor governance: (1) Pre-procurement AI risk assessment checklist. (2) Required contract clauses: data training restrictions, incident notification, audit rights, compliance obligations. (3) Ongoing monitoring: quarterly vendor compliance reviews for high-risk vendors, annual for medium-risk. (4) Vendor AI inventory maintained in the AI Registry.",
      },
    ],
  },
];

export const TELEMETRY_MATRIX = {
  headers: ["Role", "Query Text", "Response", "User Identity", "Metadata"],
  rows: [
    { role: "System Analyst", queryText: "NO", response: "NO", userIdentity: "NO", metadata: "YES" },
    { role: "Security / Compliance", queryText: "HASH ONLY", response: "NO", userIdentity: "ANONYMIZED", metadata: "YES" },
    { role: "Incident Investigation", queryText: "YES*", response: "YES*", userIdentity: "YES*", metadata: "YES" },
    { role: "Employee (own only)", queryText: "YES", response: "YES", userIdentity: "SELF", metadata: "NO" },
    { role: "AI Provider (Azure)", queryText: "YES**", response: "YES**", userIdentity: "NO", metadata: "NO" },
  ],
  footnotes: [
    "* Break-glass: requires dual approval + incident ticket + 24hr auto-expiry",
    "** Per Azure standard terms unless Enterprise Agreement opt-out is active",
    "FINDING: No opt-out active",
  ],
};
