export const CLIENT = {
  name: "Meridian Financial Group",
  industry: "Financial Services",
  aiSystem: "Internal Analytics Assistant",
  deployment: "Azure OpenAI (GPT-4o), Snowflake data warehouse",
};

// severity: "red" | "yellow" | "green"
export const LAYERS = [
  {
    id: "data",
    label: "Data Warehouse",
    subtitle: "Snowflake",
    icon: "⬡",
    summary: "Critical access control gaps with overprivileged service accounts and no row-level security.",
    findings: [
      {
        control: "Row Access Policies",
        expected: "Row-level security policies enforced per user role",
        actual: "No row access policies defined",
        severity: "red",
        remediation: "Define row access policies on all schemas containing PII or financial data. Map policies to existing AD roles via RBAC integration.",
      },
      {
        control: "Column Masking — SSN",
        expected: "SSN column masked for non-privileged roles",
        actual: "SSN column unmasked for ANALYST_ROLE",
        severity: "red",
        remediation: "Apply dynamic data masking policy on SSN column. Grant unmask privilege only to COMPLIANCE_ROLE with audit logging.",
      },
      {
        control: "AI Service Role Privileges",
        expected: "AI_SERVICE_ROLE scoped to required schemas only",
        actual: "AI_SERVICE_ROLE has SELECT on all schemas — overprivileged",
        severity: "red",
        remediation: "Restrict AI_SERVICE_ROLE to FINANCE.PUBLIC and ANALYTICS schemas only. Implement query tagging to trace AI-originated queries.",
      },
      {
        control: "Data Quality Validation",
        expected: "Validation rules enforced at ingestion pipeline",
        actual: "No validation rules on ingestion pipeline",
        severity: "yellow",
        remediation: "Implement schema validation and null-check constraints on the ingestion pipeline. Add data quality monitoring alerts.",
      },
      {
        control: "Identity Propagation",
        expected: "End-user identity propagated through to warehouse queries",
        actual: "AI_SERVICE_ROLE used for all queries regardless of requesting user",
        severity: "red",
        remediation: "Implement session-level identity propagation using Snowflake session variables. Tag every query with the originating user's identity.",
      },
    ],
  },
  {
    id: "semantic",
    label: "Semantic Layer",
    subtitle: "Metrics & Definitions",
    icon: "◈",
    summary: "74% of metrics are uncertified and in production use. No version control or conflict detection.",
    findings: [
      {
        control: "Metric Certification Rate",
        expected: "All production metrics formally certified",
        actual: "12 of 47 metrics certified (25.5%) — 35 draft/experimental metrics in production use",
        severity: "red",
        remediation: "Freeze production use of uncertified metrics. Establish a certification workflow requiring data owner sign-off before promotion.",
      },
      {
        control: "Version Control",
        expected: "Metric definitions version-controlled in Git",
        actual: "No Git integration — definitions stored in application database only",
        severity: "red",
        remediation: "Export all metric definitions to a Git repository. Implement CI/CD pipeline for definition changes with review gates.",
      },
      {
        control: "Metric Ownership",
        expected: "Every metric has a designated business owner",
        actual: "8 of 47 metrics have assigned owners",
        severity: "yellow",
        remediation: "Assign owners to all 47 metrics. Implement quarterly ownership review cadence. Unowned metrics should be flagged for deprecation.",
      },
      {
        control: "Conflict Detection",
        expected: "Automated detection of divergent KPI definitions across teams",
        actual: "No conflict detection — ANALYST_ROLE and EXEC_ROLE return different values for 'Revenue'",
        severity: "red",
        remediation: "Run a full conflict scan across all role-metric combinations. Standardize Revenue definition. Implement automated divergence detection in CI.",
      },
    ],
  },
  {
    id: "vector",
    label: "Vector Database",
    subtitle: "Retrieval Layer",
    icon: "◎",
    summary: "Document retrieval has no access scoping. PII detected in indexed HR documents.",
    findings: [
      {
        control: "Access Tag Coverage",
        expected: "All indexed documents tagged with access control metadata",
        actual: "312 of 1,247 documents tagged (25%)",
        severity: "yellow",
        remediation: "Implement mandatory access tagging in the document indexing pipeline. Backfill tags for existing 935 untagged documents.",
      },
      {
        control: "Retrieval Scope Enforcement",
        expected: "Users can only retrieve documents within their access scope",
        actual: "No scope enforcement — all users can retrieve all documents",
        severity: "red",
        remediation: "Implement pre-retrieval access filter using document access tags and user role mapping. Block retrieval of untagged documents by default.",
      },
      {
        control: "Chunk Provenance Logging",
        expected: "Every retrieved chunk logged with source document ID and retrieval context",
        actual: "No provenance logging implemented",
        severity: "red",
        remediation: "Add provenance metadata to every retrieval response: source document ID, chunk index, retrieval score, and requesting user.",
      },
      {
        control: "PII in Indexed Documents",
        expected: "No PII in document index without explicit classification",
        actual: "3 HR policy documents contain employee PII (names, SSNs)",
        severity: "red",
        remediation: "Remove PII-containing documents from index immediately. Implement PII scanning in the indexing pipeline. Re-index after remediation.",
      },
    ],
  },
  {
    id: "model",
    label: "LLM / Model Layer",
    subtitle: "Azure OpenAI",
    icon: "◉",
    summary: "No guardrails, no evaluation pipeline, and prompts may be used for provider abuse monitoring.",
    findings: [
      {
        control: "System Prompt Guardrails",
        expected: "System prompt includes behavioral constraints and output formatting rules",
        actual: "Basic role description only — no behavioral guardrails",
        severity: "yellow",
        remediation: "Enhance system prompt with explicit behavioral constraints: scope limitations, refusal patterns for out-of-scope queries, and output formatting requirements.",
      },
      {
        control: "Prompt Injection Defenses",
        expected: "Input sanitization and prompt injection detection active",
        actual: "No prompt injection defenses implemented",
        severity: "red",
        remediation: "Implement input sanitization layer. Add prompt injection detection using pattern matching and a secondary classifier. Log all blocked attempts.",
      },
      {
        control: "Confidence Scoring",
        expected: "Every response includes a calibrated confidence score",
        actual: "Not implemented",
        severity: "red",
        remediation: "Implement confidence scoring using token probability analysis. Route low-confidence responses (< 0.70) to human review queue.",
      },
      {
        control: "Citation Enforcement",
        expected: "Every factual claim in responses must cite a source document",
        actual: "Not implemented",
        severity: "red",
        remediation: "Add citation enforcement in the response generation pipeline. Require source document references for all factual claims. Flag uncitable responses.",
      },
      {
        control: "Content Safety API",
        expected: "Azure Content Safety API configured and active",
        actual: "Not configured",
        severity: "red",
        remediation: "Enable Azure Content Safety API with appropriate thresholds. Configure category-specific filters for financial services context.",
      },
      {
        control: "Evaluation Pipeline",
        expected: "Automated correctness and compliance checks on model outputs",
        actual: "No evaluation pipeline exists",
        severity: "red",
        remediation: "Build evaluation pipeline with automated test suites: factual accuracy, compliance language, scope adherence. Run on every model update.",
      },
      {
        control: "Azure Data Processing Terms",
        expected: "Enterprise Agreement with abuse monitoring opt-out active",
        actual: "Standard tier — prompts may be used for abuse monitoring",
        severity: "yellow",
        remediation: "Upgrade to Enterprise Agreement with abuse monitoring opt-out. Review Azure data processing addendum with legal team.",
      },
    ],
  },
  {
    id: "app",
    label: "Application Layer",
    subtitle: "User-Facing Controls",
    icon: "◇",
    summary: "Strong authentication in place, but no audit logging, human review, or AI disclosure to employees.",
    findings: [
      {
        control: "Authentication",
        expected: "SSO with enterprise identity provider",
        actual: "Azure AD SSO implemented",
        severity: "green",
        remediation: "No action required. SSO is properly configured.",
      },
      {
        control: "Multi-Factor Authentication",
        expected: "MFA enforced for all users",
        actual: "MFA enforced via Azure AD Conditional Access",
        severity: "green",
        remediation: "No action required. MFA is properly enforced.",
      },
      {
        control: "Structured Audit Logging",
        expected: "Every query/response pair logged with user ID, timestamp, and metadata",
        actual: "Basic application logs only — no structured query/response logging",
        severity: "red",
        remediation: "Implement structured audit logging: user ID, timestamp, query text (hashed), response hash, confidence score, retrieval sources. Store in immutable log.",
      },
      {
        control: "Human Review Queue",
        expected: "Low-confidence and high-risk responses routed for human review",
        actual: "No human review queue exists",
        severity: "red",
        remediation: "Build human review queue with configurable routing rules. Route responses with confidence < 0.70 and all financial/compliance queries for review.",
      },
      {
        control: "Anomaly Detection",
        expected: "Behavioral anomaly detection on query patterns",
        actual: "No anomaly detection implemented",
        severity: "red",
        remediation: "Implement anomaly detection on query volume, topic distribution, and access patterns. Alert on statistical deviations from baseline.",
      },
      {
        control: "Employee AI Usage Disclosure",
        expected: "AI usage policy communicated to all employees with acknowledgment",
        actual: "No AI usage policy communicated to employees",
        severity: "red",
        remediation: "Draft and distribute AI Transparency & Usage Policy. Require employee acknowledgment. Include: what is logged, who can access logs, employee rights.",
      },
    ],
  },
];

export const TELEMETRY_MATRIX = {
  headers: ["Role", "Query Text", "Response", "User Identity", "Metadata"],
  rows: [
    { role: "System Analyst", queryText: "NO", response: "NO", userIdentity: "NO", metadata: "YES" },
    { role: "Security / Compliance", queryText: "HASH ONLY", response: "NO", userIdentity: "ANONYMIZED", metadata: "YES" },
    { role: "Incident Investigation", queryText: "YES*", response: "YES*", userIdentity: "YES*", metadata: "YES" },
    { role: "Employee (own only)", queryText: "YES", response: "YES", userIdentity: "SELF", metadata: "NO" },
    { role: "AI Provider (Azure)", queryText: "YES**", response: "YES**", userIdentity: "NO", metadata: "NO" },
  ],
  footnotes: [
    "* Break-glass: requires dual approval + incident ticket + 24hr auto-expiry",
    "** Per Azure standard terms unless Enterprise Agreement opt-out is active",
    "FINDING: No opt-out active",
  ],
};
